#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export EDITOR='nvim'
export TERMINAL='kitty'
export BROWSER='brave'
export HISTCONTROL='ignoreboth'
export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export PATH=$HOME/.fnm:$PATH
export PATH=$HOME/Android/Sdk/platform-tools:$PATH
export PATH=$HOME/node_modules/.bin:$PATH
export PATH=/usr/local/texlive/2021/bin/x86_64-linux:$PATH
