#!/bin/sh
alias cp='xcp'
alias rm='rip'
alias cat='bat'
alias gg='lazygit'
alias gs='git status'
alias gss='git stash'
alias gsp='git stash pop'
alias gc='git commit'
alias gp='git push'
alias ga='git add'
alias gf='git flow'
alias dcu='docker-compose up --remove-orphans'
alias dcub='docker-compose up --remove-orphans --build'
alias dcd='docker-compose down'

# KITTY
alias s="kitty +kitten ssh"
alias icat="kitty +kitten icat"

# BP
alias latexmkbp='latexmk -xelatex -shell-escape -synctex=1 -interaction=nonstopmode -file-line-error "kerckhof_edward_voorstel"'

alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias nvimrc='nvim ~/.config/nvim/'
alias lvimrc='nvim ~/.config/lvim/config.lua'

# get fastest mirrors
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# For when keys break
alias archlinx-fix-keys="sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman-key --refresh-keys"

alias doas='doas --'                                        # root privileges
alias ls='exa -al --color=always --group-directories-first' # my preferred listing
alias la='exa -a --color=always --group-directories-first'  # all files and dirs
alias ll='exa -l --color=always --group-directories-first'  # long format
alias lt='exa -aT --color=always --group-directories-first' # tree listing
alias update='paru -Sua'                                    # update standard pkgs and AUR pkgs (paru)
alias cleanup='sudo pacman -Rns (pacman -Qtdq)'             # remove orphaned packages

# dotfiles alias
alias dotfiles='/usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME'

# youtube-dl
alias yta-aac='youtube-dl --extract-audio --audio-format aac'
alias yta-best='youtube-dl --extract-audio --audio-format best'
alias yta-flac='youtube-dl --extract-audio --audio-format flac'
alias yta-m4a='youtube-dl --extract-audio --audio-format m4a'
alias yta-mp3='youtube-dl --extract-audio --audio-format mp3'
alias yta-wav='youtube-dl --extract-audio --audio-format wav'
alias ytv-best='youtube-dl -f bestvideo+bestaudio'

# nvim
alias vim='lvim'
alias vi='lvim'
alias v='lvim'

# emacs
alias emacs="emacsclient -c -a 'emacs'"

# yay / pacman
alias yay='paru'

# fnm /nvm
alias nvm='fnm'

# luamake
alias luamake=/home/edward/language-servers/lua-language-server/3rd/luamake/luamake

# Fuzzy file searching
alias fz='rg --files --hidden --follow --no-ignore-vcs -g "!{node_modules,.git}" | fzf'

# RL
alias runelite=/opt/RuneLite.AppImage
